---
pool: Default
 
trigger:
  - main
stages:
  - stage: ansiblepipeline
    jobs:
      - job: java11
        displayName: java is installing
        steps:
          - script: |
              ansible-playbook -i hosts ansible.yaml